# docker-compose.yml (Production Base File)
# version: '3.8'

services:
  # 1. Laravel PHP-FPM Service
  bus-ticket-app:
    image: kaziomar/bus-ticket-app:latest # importing from Docker Hub
    container_name: bus-ticket-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www 
      - /var/www/vendor
      - ./backend/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=bus-ticket-db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - bus-ticket-network
    depends_on:
      - bus-ticket-db

  # 2. Laravel Web Server (Nginx)
  backend-webserver:
    image: nginx:stable-alpine
    container_name: bus-ticket-nginx-server
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
      - ./backend/nginx_config/:/etc/nginx/conf.d
    networks:
      - bus-ticket-network
    depends_on:
      - bus-ticket-app

  # 3. Database Service (MySQL)
  bus-ticket-db:
    image: mysql:8.0
    container_name: bus-ticket-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bus-ticket-network
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 6. Main Nginx Reverse Proxy Service
  nginx-proxy:
    image: kaziomar/bus-ticket-nginx-proxy:latest # importing from Docker Hub
    container_name: bus-ticket-nginx
    restart: unless-stopped
    ports:
      - "82:80" # For server use "80:80"
      - "4454:443" # For server use "443:443"
    networks:
      - bus-ticket-network
    depends_on:
      - backend-webserver

  # Queue Worker
  queue-worker:
    image: kaziomar/bus-ticket-app:latest # importing from Docker Hub
    container_name: bus-ticket-queue-worker
    command: php artisan queue:work --sleep=3 --tries=3
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    environment: 
      - DB_CONNECTION=mysql
      - DB_HOST=bus-ticket-db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - bus-ticket-network
    depends_on:
      bus-ticket-app:
        condition: service_started
      bus-ticket-db:
        condition: service_healthy

  # Scheduler
  scheduler:
    image: kaziomar/bus-ticket-app:latest # importing from Docker Hub
    container_name: bus-ticket-scheduler
    command: sh -c "while true; do php /var/www/artisan schedule:run; sleep 60; done"
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    environment: 
      - DB_CONNECTION=mysql
      - DB_HOST=bus-ticket-db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - bus-ticket-network
    depends_on:
      bus-ticket-app:
        condition: service_started
      bus-ticket-db:
        condition: service_healthy

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: bus-ticket-phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80" # For server use "8080:80"
    environment:
      PMA_HOST: bus-ticket-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    networks:
      - bus-ticket-network
  
  # Redis Service
  bus-ticket-redis:
    image: redis:7-alpine 
    container_name: bus-ticket-redis
    restart: unless-stopped
    volumes:
      - bus-ticket-redis-data:/data
    networks:
      - bus-ticket-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  reverb:
    image: kaziomar/bus-ticket-app:latest # importing from Docker Hub 
    container_name: bus-ticket-reverb
    command: php artisan reverb:start --host="0.0.0.0" --port="8080"
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    environment: 
      - DB_CONNECTION=mysql
      - DB_HOST=bus-ticket-db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=bus-ticket-redis
      - REVERB_APP_ID=${REVERB_APP_ID}
      - REVERB_APP_KEY=${REVERB_APP_KEY}
      - REVERB_APP_SECRET=${REVERB_APP_SECRET}
    networks:
      - bus-ticket-network
    depends_on:
      - bus-ticket-app
      - bus-ticket-redis


# Networks and Volumes
networks:
  bus-ticket-network:
    driver: bridge

volumes:
  db_data:
  bus-ticket-redis-data:
    driver: local